### PR TITLE
Fixing terraform apply comments

### LINKED ISSUE #97: Terraform apply comments for succeeded steps
Whenever apply succeeded, can it comment pull_request?
I may missed something, but it doesnt seems so.

### PR DESCRIPTION
**Pull request by canelkatmis**
Fixes #97

### CODE REVIEW

**Comment by canelkatmis** [comment]
Thanks, done

File: src/terraform_apply.sh [hunk 1]
```diff
@@ -5,23 +5,26 @@ function terraformApply {
...
   # Exit code of 0 indicates success. Print the output and exit.
   if [ ${applyExitCode} -eq 0 ]; then
     echo "apply: info: successfully applied Terraform configuration in ${tfWorkingDir}"
     echo "${applyOutput}"
     echo
-    exit ${applyExitCode}
+    applyCommentStatus="Success"
   fi
-
+
```
Comment (sudomateo) [inline src/terraform_apply.sh]: Would you be so kind and remove this extra whitespace? Otherwise it looks good!

**Comment by sudomateo** [comment]
I'll release this as `0.5.4` tomorrow when I'm at a computer.
